spring:
  mvc:
    cors:
      allowed-origins=*:
  main:
    allow-bean-definition-overriding: true
  cache:
    type: simple
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:8080
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics,prometheus

toggle:
  service: ${SERVICE_TYPE:azureBlob} # redis or azureBlob

azure:
  blob:
    container-name: toggles
    connection-string: ${AZURE_BLOB_CONNECTION_STRING}

logging:
  level:
    root=INFO: