spring:
  main:
    allow-bean-definition-overriding: true
  cache:
    type: simple
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

toggle:
  service: azureBlob # redis or azureBlob

logging:
  level:
    root=INFO: